[supervisord]
nodaemon=true

[program:valkey]
command=valkey-server
autostart=true
autorestart=true

[program:api]
command=uv run uvicorn main:app --host 0.0.0.0 --port 8081
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
